/*
 * Copyright (c) 2023 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/net/wifi_mgmt.h>

/* Connectivity Events */
#define _NET_MGMT_SUPPLICANT_LAYER NET_MGMT_LAYER_L3
#define _NET_MGMT_SUPPLICANT_CODE 0x157
#define _NET_MGMT_SUPPLICANT_BASE (NET_MGMT_LAYER(_NET_MGMT_SUPPLICANT_LAYER) | \
				NET_MGMT_LAYER_CODE(_NET_MGMT_SUPPLICANT_CODE) | \
				NET_MGMT_IFACE_BIT)
#define _NET_MGMT_SUPPLICANT_EVENT (NET_MGMT_EVENT_BIT | _NET_MGMT_SUPPLICANT_BASE)

enum net_event_supplicant_cmd {
	NET_EVENT_SUPPLICANT_CMD_READY = 1,
	NET_EVENT_SUPPLICANT_CMD_NOT_READY,
	NET_EVENT_SUPPLICANT_CMD_IFACE_ADDED,
	NET_EVENT_SUPPLICANT_CMD_IFACE_REMOVING,
	NET_EVENT_SUPPLICANT_CMD_IFACE_REMOVED,
	NET_EVENT_WIFI_CMD_MAX
};

#define NET_EVENT_SUPPLICANT_READY					\
	(_NET_MGMT_SUPPLICANT_EVENT | NET_EVENT_SUPPLICANT_CMD_READY)

#define NET_EVENT_SUPPLICANT_NOT_READY					\
	(_NET_MGMT_SUPPLICANT_EVENT | NET_EVENT_SUPPLICANT_CMD_NOT_READY)

#define NET_EVENT_SUPPLICANT_IFACE_ADDED					\
	(_NET_MGMT_SUPPLICANT_EVENT | NET_EVENT_SUPPLICANT_CMD_IFACE_ADDED)

#define NET_EVENT_SUPPLICANT_IFACE_REMOVED					\
	(_NET_MGMT_SUPPLICANT_EVENT | NET_EVENT_SUPPLICANT_CMD_IFACE_REMOVED)

#define NET_EVENT_SUPPLICANT_IFACE_REMOVING					\
	(_NET_MGMT_SUPPLICANT_EVENT | NET_EVENT_SUPPLICANT_CMD_IFACE_REMOVING)

int supplicant_send_wifi_mgmt_event(const char *ifname, enum net_event_wifi_cmd event, int status);
int supplicant_generate_state_event(const char *ifname, enum net_event_supplicant_cmd event, int status);
